version: '1'

services:
  web:
    build: .
    command: python manage.py runsrver 0.0.0.0:8000
    vloumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
